window:
  gtk_theme_variant: dark

font:
  normal:
    family: Operator Mono for Powerline
    style: Regular
  bold:
    family: Operator Mono for Powerline
    style: Bold
  italic:
    family: Operator Mono for Powerline
    style: Italic
  bold_italic:
    family: Operator Mono for Powerline
    style: Bold Italic

draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: true

custom_cursor_colors: true

colors:
  cursor:
    cursor: '0xffffff'

    #cursor:
  #  style:
    #    shape: Underline
    #  vi_mode_style: underscore

live_config_reload: true

shell:
  program: wsl.exe
